// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/speech/fireworks-admin/internal/ent/schema"
	"github.com/speech/fireworks-admin/internal/ent/teltent"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	teltentMixin := schema.Teltent{}.Mixin()
	teltentMixinFields0 := teltentMixin[0].Fields()
	_ = teltentMixinFields0
	teltentMixinFields2 := teltentMixin[2].Fields()
	_ = teltentMixinFields2
	teltentMixinFields3 := teltentMixin[3].Fields()
	_ = teltentMixinFields3
	teltentFields := schema.Teltent{}.Fields()
	_ = teltentFields
	// teltentDescCreatedAt is the schema descriptor for created_at field.
	teltentDescCreatedAt := teltentMixinFields2[0].Descriptor()
	// teltent.DefaultCreatedAt holds the default value on creation for the created_at field.
	teltent.DefaultCreatedAt = teltentDescCreatedAt.Default.(func() time.Time)
	// teltentDescUpdatedAt is the schema descriptor for updated_at field.
	teltentDescUpdatedAt := teltentMixinFields3[0].Descriptor()
	// teltent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	teltent.DefaultUpdatedAt = teltentDescUpdatedAt.Default.(func() time.Time)
	// teltent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	teltent.UpdateDefaultUpdatedAt = teltentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// teltentDescCertificateNo is the schema descriptor for certificate_no field.
	teltentDescCertificateNo := teltentFields[0].Descriptor()
	// teltent.CertificateNoValidator is a validator for the "certificate_no" field. It is called by the builders before save.
	teltent.CertificateNoValidator = func() func(string) error {
		validators := teltentDescCertificateNo.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(certificate_no string) error {
			for _, fn := range fns {
				if err := fn(certificate_no); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// teltentDescName is the schema descriptor for name field.
	teltentDescName := teltentFields[1].Descriptor()
	// teltent.NameValidator is a validator for the "name" field. It is called by the builders before save.
	teltent.NameValidator = func() func(string) error {
		validators := teltentDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// teltentDescType is the schema descriptor for type field.
	teltentDescType := teltentFields[2].Descriptor()
	// teltent.DefaultType holds the default value on creation for the type field.
	teltent.DefaultType = teltentDescType.Default.(int8)
	// teltent.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	teltent.TypeValidator = func() func(int8) error {
		validators := teltentDescType.Validators
		fns := [...]func(int8) error{
			validators[0].(func(int8) error),
			validators[1].(func(int8) error),
		}
		return func(_type int8) error {
			for _, fn := range fns {
				if err := fn(_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// teltentDescContactName is the schema descriptor for contact_name field.
	teltentDescContactName := teltentFields[3].Descriptor()
	// teltent.ContactNameValidator is a validator for the "contact_name" field. It is called by the builders before save.
	teltent.ContactNameValidator = func() func(string) error {
		validators := teltentDescContactName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(contact_name string) error {
			for _, fn := range fns {
				if err := fn(contact_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// teltentDescEmail is the schema descriptor for email field.
	teltentDescEmail := teltentFields[4].Descriptor()
	// teltent.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	teltent.EmailValidator = func() func(string) error {
		validators := teltentDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// teltentDescPhone is the schema descriptor for phone field.
	teltentDescPhone := teltentFields[5].Descriptor()
	// teltent.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	teltent.PhoneValidator = func() func(string) error {
		validators := teltentDescPhone.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(phone string) error {
			for _, fn := range fns {
				if err := fn(phone); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// teltentDescID is the schema descriptor for id field.
	teltentDescID := teltentMixinFields0[0].Descriptor()
	// teltent.DefaultID holds the default value on creation for the id field.
	teltent.DefaultID = teltentDescID.Default.(func() uuid.UUID)
}
