// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/speech/fireworks-admin/internal/ent/schema"
	"github.com/speech/fireworks-admin/internal/ent/tenant"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tenantMixin := schema.Tenant{}.Mixin()
	tenantMixinFields0 := tenantMixin[0].Fields()
	_ = tenantMixinFields0
	tenantMixinFields2 := tenantMixin[2].Fields()
	_ = tenantMixinFields2
	tenantMixinFields3 := tenantMixin[3].Fields()
	_ = tenantMixinFields3
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantMixinFields2[0].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantMixinFields3[0].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantDescCertificateNo is the schema descriptor for certificate_no field.
	tenantDescCertificateNo := tenantFields[0].Descriptor()
	// tenant.CertificateNoValidator is a validator for the "certificate_no" field. It is called by the builders before save.
	tenant.CertificateNoValidator = func() func(string) error {
		validators := tenantDescCertificateNo.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(certificate_no string) error {
			for _, fn := range fns {
				if err := fn(certificate_no); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[1].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = func() func(string) error {
		validators := tenantDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescType is the schema descriptor for type field.
	tenantDescType := tenantFields[2].Descriptor()
	// tenant.DefaultType holds the default value on creation for the type field.
	tenant.DefaultType = tenantDescType.Default.(int8)
	// tenant.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	tenant.TypeValidator = func() func(int8) error {
		validators := tenantDescType.Validators
		fns := [...]func(int8) error{
			validators[0].(func(int8) error),
			validators[1].(func(int8) error),
		}
		return func(_type int8) error {
			for _, fn := range fns {
				if err := fn(_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescContactName is the schema descriptor for contact_name field.
	tenantDescContactName := tenantFields[3].Descriptor()
	// tenant.ContactNameValidator is a validator for the "contact_name" field. It is called by the builders before save.
	tenant.ContactNameValidator = func() func(string) error {
		validators := tenantDescContactName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(contact_name string) error {
			for _, fn := range fns {
				if err := fn(contact_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescEmail is the schema descriptor for email field.
	tenantDescEmail := tenantFields[4].Descriptor()
	// tenant.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	tenant.EmailValidator = func() func(string) error {
		validators := tenantDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescPhone is the schema descriptor for phone field.
	tenantDescPhone := tenantFields[5].Descriptor()
	// tenant.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	tenant.PhoneValidator = func() func(string) error {
		validators := tenantDescPhone.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(phone string) error {
			for _, fn := range fns {
				if err := fn(phone); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantMixinFields0[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() uuid.UUID)
}
