// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/speech/fireworks-admin/internal/di/provider"
	"github.com/speech/fireworks-admin/internal/infrastructure/config"
	"github.com/speech/fireworks-admin/internal/infrastructure/http/handle"
	"github.com/speech/fireworks-admin/internal/infrastructure/persistence/ent"
	"log/slog"
)

// Injectors from wire.go:

// InitializeApp 初始化应用依赖
// 该函数由 wire 自动生成实现，用于创建所有依赖组件
// 返回:
//   - *App: 应用依赖容器
//   - func(): 清理函数
//   - error: 初始化错误
func InitializeApp() (*App, func(), error) {
	config, err := provider.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	logger := provider.ProvideLogger(config)
	string2 := provider.ProvideDSN(config)
	client, cleanup, err := provider.ProvideEntClient(string2)
	if err != nil {
		return nil, nil, err
	}
	teltentRepo := provider.ProvideTeltentRepo(client)
	teltentUsecase := provider.ProvideTeltentUsecase(teltentRepo)
	teltentHandle := provider.ProvideTeltentHandle(teltentUsecase)
	app := &App{
		Config:        config,
		Logger:        logger,
		EntClient:     client,
		TeltentHandle: teltentHandle,
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// App 应用依赖容器
// 包含所有需要注入的依赖组件
type App struct {
	Config        *config.Config
	Logger        *slog.Logger
	EntClient     *ent.Client
	TeltentHandle *handle.TeltentHandle
}
