// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/speech/fireworks-admin/internal/features/tenant"
	"github.com/speech/fireworks-admin/internal/features/user"
	"github.com/speech/fireworks-admin/internal/pkg/config"
	"github.com/speech/fireworks-admin/internal/pkg/db"
	"github.com/speech/fireworks-admin/internal/pkg/lifecycle"
	"github.com/speech/fireworks-admin/internal/pkg/logger"
)

// Injectors from wire.go:

// InitializeApp 初始化应用依赖。
// 该函数由 Wire 框架自动生成实现代码（见 wire_gen.go）。
// 通过组合多个 ProviderSet 和提供者函数，构建完整的应用依赖图。
// 返回初始化完成的 App 实例或错误。
func InitializeApp() (*App, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	slogLogger := logger.ProvideLogger(configConfig)
	lifecycleLifecycle := lifecycle.NewLifecycle()
	client, err := db.NewEntClient(lifecycleLifecycle, configConfig)
	if err != nil {
		return nil, err
	}
	txManager := db.NewTxManager(client)
	tenantRepo := tenant.NewTenantRepo(txManager)
	tenantService := tenant.NewTenantService(tenantRepo)
	tenantHandler := tenant.NewTenantHandler(tenantService)
	userRepo := user.NewUserRepo(txManager)
	userService := user.NewUserService(userRepo)
	userHandler := user.NewUserHandler(userService)
	healthRouter := NewHealthRouter(client)
	registrarIn := RegistrarIn{
		Tenant: tenantHandler,
		User:   userHandler,
		Health: healthRouter,
	}
	v := ProvideRegistrars(registrarIn)
	echo := NewEcho(slogLogger, configConfig, v)
	server := NewServer(echo, configConfig, lifecycleLifecycle)
	app := &App{
		Config:     configConfig,
		Logger:     slogLogger,
		EntClient:  client,
		Registrars: v,
		Lifecycle:  lifecycleLifecycle,
		Server:     server,
	}
	return app, nil
}
