// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/speech/fireworks-admin/internal/features/teltent"
	"github.com/speech/fireworks-admin/internal/pkg/config"
	"github.com/speech/fireworks-admin/internal/pkg/db"
	"github.com/speech/fireworks-admin/internal/pkg/logger"
)

// Injectors from wire.go:

// InitializeApp 初始化应用依赖。
func InitializeApp() (*App, func(), error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	slogLogger := logger.ProvideLogger(configConfig)
	client, cleanup, err := db.NewEntClient(configConfig)
	if err != nil {
		return nil, nil, err
	}
	repository := teltent.NewRepository(client)
	service := teltent.NewService(repository)
	handler := teltent.NewHandler(service)
	app := &App{
		Config:         configConfig,
		Logger:         slogLogger,
		EntClient:      client,
		TeltentHandler: handler,
	}
	return app, func() {
		cleanup()
	}, nil
}
