// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TeltentsColumns holds the columns for the "teltents" table.
	TeltentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "status", Type: field.TypeInt8},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "certificate_no", Type: field.TypeString, Size: 50},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "type", Type: field.TypeInt8, Default: 1},
		{Name: "contact_name", Type: field.TypeString, Size: 50},
		{Name: "email", Type: field.TypeString, Size: 255},
		{Name: "phone", Type: field.TypeString, Size: 20},
		{Name: "expired_at", Type: field.TypeTime, Nullable: true},
	}
	// TeltentsTable holds the schema information for the "teltents" table.
	TeltentsTable = &schema.Table{
		Name:       "teltents",
		Columns:    TeltentsColumns,
		PrimaryKey: []*schema.Column{TeltentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "uk_email",
				Unique:  true,
				Columns: []*schema.Column{TeltentsColumns[9]},
				Annotation: &entsql.IndexAnnotation{
					Where: "deleted_at IS NULL",
				},
			},
			{
				Name:    "uk_phone",
				Unique:  true,
				Columns: []*schema.Column{TeltentsColumns[10]},
				Annotation: &entsql.IndexAnnotation{
					Where: "deleted_at IS NULL",
				},
			},
			{
				Name:    "uk_certificate_no",
				Unique:  true,
				Columns: []*schema.Column{TeltentsColumns[5]},
				Annotation: &entsql.IndexAnnotation{
					Where: "deleted_at IS NULL",
				},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TeltentsTable,
	}
)

func init() {
}
