// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TeltentsColumns holds the columns for the "teltents" table.
	TeltentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "status", Type: field.TypeInt8},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "certificate_no", Type: field.TypeString, Unique: true, Size: 50},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "type", Type: field.TypeInt8, Default: 1},
		{Name: "contact_name", Type: field.TypeString, Size: 50},
		{Name: "email", Type: field.TypeString, Size: 255},
		{Name: "phone", Type: field.TypeString, Size: 20},
		{Name: "expired_at", Type: field.TypeTime, Nullable: true},
	}
	// TeltentsTable holds the schema information for the "teltents" table.
	TeltentsTable = &schema.Table{
		Name:       "teltents",
		Columns:    TeltentsColumns,
		PrimaryKey: []*schema.Column{TeltentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_phone_id",
				Unique:  false,
				Columns: []*schema.Column{TeltentsColumns[10], TeltentsColumns[0]},
			},
			{
				Name:    "idx_email_id",
				Unique:  false,
				Columns: []*schema.Column{TeltentsColumns[9], TeltentsColumns[0]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TeltentsTable,
	}
)

func init() {
}
