// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/speech/fireworks-admin/internal/infrastructure/persistence/ent/predicate"
	"github.com/speech/fireworks-admin/internal/infrastructure/persistence/ent/teltent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeTeltent = "Teltent"
)

// TeltentMutation represents an operation that mutates the Teltent nodes in the graph.
type TeltentMutation struct {
	config
	op             Op
	typ            string
	id             *uuid.UUID
	status         *int8
	addstatus      *int8
	created_at     *time.Time
	updated_at     *time.Time
	deleted_at     *time.Time
	certificate_no *string
	name           *string
	_type          *int8
	add_type       *int8
	contact_name   *string
	email          *string
	phone          *string
	expired_at     *time.Time
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*Teltent, error)
	predicates     []predicate.Teltent
}

var _ ent.Mutation = (*TeltentMutation)(nil)

// teltentOption allows management of the mutation configuration using functional options.
type teltentOption func(*TeltentMutation)

// newTeltentMutation creates new mutation for the Teltent entity.
func newTeltentMutation(c config, op Op, opts ...teltentOption) *TeltentMutation {
	m := &TeltentMutation{
		config:        c,
		op:            op,
		typ:           TypeTeltent,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTeltentID sets the ID field of the mutation.
func withTeltentID(id uuid.UUID) teltentOption {
	return func(m *TeltentMutation) {
		var (
			err   error
			once  sync.Once
			value *Teltent
		)
		m.oldValue = func(ctx context.Context) (*Teltent, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Teltent.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTeltent sets the old Teltent of the mutation.
func withTeltent(node *Teltent) teltentOption {
	return func(m *TeltentMutation) {
		m.oldValue = func(context.Context) (*Teltent, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TeltentMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TeltentMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Teltent entities.
func (m *TeltentMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TeltentMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TeltentMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Teltent.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetStatus sets the "status" field.
func (m *TeltentMutation) SetStatus(i int8) {
	m.status = &i
	m.addstatus = nil
}

// Status returns the value of the "status" field in the mutation.
func (m *TeltentMutation) Status() (r int8, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Teltent entity.
// If the Teltent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TeltentMutation) OldStatus(ctx context.Context) (v int8, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// AddStatus adds i to the "status" field.
func (m *TeltentMutation) AddStatus(i int8) {
	if m.addstatus != nil {
		*m.addstatus += i
	} else {
		m.addstatus = &i
	}
}

// AddedStatus returns the value that was added to the "status" field in this mutation.
func (m *TeltentMutation) AddedStatus() (r int8, exists bool) {
	v := m.addstatus
	if v == nil {
		return
	}
	return *v, true
}

// ResetStatus resets all changes to the "status" field.
func (m *TeltentMutation) ResetStatus() {
	m.status = nil
	m.addstatus = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *TeltentMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *TeltentMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Teltent entity.
// If the Teltent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TeltentMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *TeltentMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *TeltentMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *TeltentMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Teltent entity.
// If the Teltent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TeltentMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *TeltentMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetDeletedAt sets the "deleted_at" field.
func (m *TeltentMutation) SetDeletedAt(t time.Time) {
	m.deleted_at = &t
}

// DeletedAt returns the value of the "deleted_at" field in the mutation.
func (m *TeltentMutation) DeletedAt() (r time.Time, exists bool) {
	v := m.deleted_at
	if v == nil {
		return
	}
	return *v, true
}

// OldDeletedAt returns the old "deleted_at" field's value of the Teltent entity.
// If the Teltent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TeltentMutation) OldDeletedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeletedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeletedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeletedAt: %w", err)
	}
	return oldValue.DeletedAt, nil
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (m *TeltentMutation) ClearDeletedAt() {
	m.deleted_at = nil
	m.clearedFields[teltent.FieldDeletedAt] = struct{}{}
}

// DeletedAtCleared returns if the "deleted_at" field was cleared in this mutation.
func (m *TeltentMutation) DeletedAtCleared() bool {
	_, ok := m.clearedFields[teltent.FieldDeletedAt]
	return ok
}

// ResetDeletedAt resets all changes to the "deleted_at" field.
func (m *TeltentMutation) ResetDeletedAt() {
	m.deleted_at = nil
	delete(m.clearedFields, teltent.FieldDeletedAt)
}

// SetCertificateNo sets the "certificate_no" field.
func (m *TeltentMutation) SetCertificateNo(s string) {
	m.certificate_no = &s
}

// CertificateNo returns the value of the "certificate_no" field in the mutation.
func (m *TeltentMutation) CertificateNo() (r string, exists bool) {
	v := m.certificate_no
	if v == nil {
		return
	}
	return *v, true
}

// OldCertificateNo returns the old "certificate_no" field's value of the Teltent entity.
// If the Teltent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TeltentMutation) OldCertificateNo(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCertificateNo is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCertificateNo requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCertificateNo: %w", err)
	}
	return oldValue.CertificateNo, nil
}

// ResetCertificateNo resets all changes to the "certificate_no" field.
func (m *TeltentMutation) ResetCertificateNo() {
	m.certificate_no = nil
}

// SetName sets the "name" field.
func (m *TeltentMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *TeltentMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Teltent entity.
// If the Teltent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TeltentMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *TeltentMutation) ResetName() {
	m.name = nil
}

// SetType sets the "type" field.
func (m *TeltentMutation) SetType(i int8) {
	m._type = &i
	m.add_type = nil
}

// GetType returns the value of the "type" field in the mutation.
func (m *TeltentMutation) GetType() (r int8, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the Teltent entity.
// If the Teltent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TeltentMutation) OldType(ctx context.Context) (v int8, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// AddType adds i to the "type" field.
func (m *TeltentMutation) AddType(i int8) {
	if m.add_type != nil {
		*m.add_type += i
	} else {
		m.add_type = &i
	}
}

// AddedType returns the value that was added to the "type" field in this mutation.
func (m *TeltentMutation) AddedType() (r int8, exists bool) {
	v := m.add_type
	if v == nil {
		return
	}
	return *v, true
}

// ResetType resets all changes to the "type" field.
func (m *TeltentMutation) ResetType() {
	m._type = nil
	m.add_type = nil
}

// SetContactName sets the "contact_name" field.
func (m *TeltentMutation) SetContactName(s string) {
	m.contact_name = &s
}

// ContactName returns the value of the "contact_name" field in the mutation.
func (m *TeltentMutation) ContactName() (r string, exists bool) {
	v := m.contact_name
	if v == nil {
		return
	}
	return *v, true
}

// OldContactName returns the old "contact_name" field's value of the Teltent entity.
// If the Teltent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TeltentMutation) OldContactName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContactName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContactName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContactName: %w", err)
	}
	return oldValue.ContactName, nil
}

// ResetContactName resets all changes to the "contact_name" field.
func (m *TeltentMutation) ResetContactName() {
	m.contact_name = nil
}

// SetEmail sets the "email" field.
func (m *TeltentMutation) SetEmail(s string) {
	m.email = &s
}

// Email returns the value of the "email" field in the mutation.
func (m *TeltentMutation) Email() (r string, exists bool) {
	v := m.email
	if v == nil {
		return
	}
	return *v, true
}

// OldEmail returns the old "email" field's value of the Teltent entity.
// If the Teltent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TeltentMutation) OldEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmail: %w", err)
	}
	return oldValue.Email, nil
}

// ResetEmail resets all changes to the "email" field.
func (m *TeltentMutation) ResetEmail() {
	m.email = nil
}

// SetPhone sets the "phone" field.
func (m *TeltentMutation) SetPhone(s string) {
	m.phone = &s
}

// Phone returns the value of the "phone" field in the mutation.
func (m *TeltentMutation) Phone() (r string, exists bool) {
	v := m.phone
	if v == nil {
		return
	}
	return *v, true
}

// OldPhone returns the old "phone" field's value of the Teltent entity.
// If the Teltent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TeltentMutation) OldPhone(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPhone is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPhone requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPhone: %w", err)
	}
	return oldValue.Phone, nil
}

// ResetPhone resets all changes to the "phone" field.
func (m *TeltentMutation) ResetPhone() {
	m.phone = nil
}

// SetExpiredAt sets the "expired_at" field.
func (m *TeltentMutation) SetExpiredAt(t time.Time) {
	m.expired_at = &t
}

// ExpiredAt returns the value of the "expired_at" field in the mutation.
func (m *TeltentMutation) ExpiredAt() (r time.Time, exists bool) {
	v := m.expired_at
	if v == nil {
		return
	}
	return *v, true
}

// OldExpiredAt returns the old "expired_at" field's value of the Teltent entity.
// If the Teltent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TeltentMutation) OldExpiredAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpiredAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpiredAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpiredAt: %w", err)
	}
	return oldValue.ExpiredAt, nil
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (m *TeltentMutation) ClearExpiredAt() {
	m.expired_at = nil
	m.clearedFields[teltent.FieldExpiredAt] = struct{}{}
}

// ExpiredAtCleared returns if the "expired_at" field was cleared in this mutation.
func (m *TeltentMutation) ExpiredAtCleared() bool {
	_, ok := m.clearedFields[teltent.FieldExpiredAt]
	return ok
}

// ResetExpiredAt resets all changes to the "expired_at" field.
func (m *TeltentMutation) ResetExpiredAt() {
	m.expired_at = nil
	delete(m.clearedFields, teltent.FieldExpiredAt)
}

// Where appends a list predicates to the TeltentMutation builder.
func (m *TeltentMutation) Where(ps ...predicate.Teltent) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TeltentMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TeltentMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Teltent, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TeltentMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TeltentMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Teltent).
func (m *TeltentMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TeltentMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.status != nil {
		fields = append(fields, teltent.FieldStatus)
	}
	if m.created_at != nil {
		fields = append(fields, teltent.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, teltent.FieldUpdatedAt)
	}
	if m.deleted_at != nil {
		fields = append(fields, teltent.FieldDeletedAt)
	}
	if m.certificate_no != nil {
		fields = append(fields, teltent.FieldCertificateNo)
	}
	if m.name != nil {
		fields = append(fields, teltent.FieldName)
	}
	if m._type != nil {
		fields = append(fields, teltent.FieldType)
	}
	if m.contact_name != nil {
		fields = append(fields, teltent.FieldContactName)
	}
	if m.email != nil {
		fields = append(fields, teltent.FieldEmail)
	}
	if m.phone != nil {
		fields = append(fields, teltent.FieldPhone)
	}
	if m.expired_at != nil {
		fields = append(fields, teltent.FieldExpiredAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TeltentMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case teltent.FieldStatus:
		return m.Status()
	case teltent.FieldCreatedAt:
		return m.CreatedAt()
	case teltent.FieldUpdatedAt:
		return m.UpdatedAt()
	case teltent.FieldDeletedAt:
		return m.DeletedAt()
	case teltent.FieldCertificateNo:
		return m.CertificateNo()
	case teltent.FieldName:
		return m.Name()
	case teltent.FieldType:
		return m.GetType()
	case teltent.FieldContactName:
		return m.ContactName()
	case teltent.FieldEmail:
		return m.Email()
	case teltent.FieldPhone:
		return m.Phone()
	case teltent.FieldExpiredAt:
		return m.ExpiredAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TeltentMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case teltent.FieldStatus:
		return m.OldStatus(ctx)
	case teltent.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case teltent.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case teltent.FieldDeletedAt:
		return m.OldDeletedAt(ctx)
	case teltent.FieldCertificateNo:
		return m.OldCertificateNo(ctx)
	case teltent.FieldName:
		return m.OldName(ctx)
	case teltent.FieldType:
		return m.OldType(ctx)
	case teltent.FieldContactName:
		return m.OldContactName(ctx)
	case teltent.FieldEmail:
		return m.OldEmail(ctx)
	case teltent.FieldPhone:
		return m.OldPhone(ctx)
	case teltent.FieldExpiredAt:
		return m.OldExpiredAt(ctx)
	}
	return nil, fmt.Errorf("unknown Teltent field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TeltentMutation) SetField(name string, value ent.Value) error {
	switch name {
	case teltent.FieldStatus:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case teltent.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case teltent.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case teltent.FieldDeletedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeletedAt(v)
		return nil
	case teltent.FieldCertificateNo:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCertificateNo(v)
		return nil
	case teltent.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case teltent.FieldType:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case teltent.FieldContactName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContactName(v)
		return nil
	case teltent.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmail(v)
		return nil
	case teltent.FieldPhone:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPhone(v)
		return nil
	case teltent.FieldExpiredAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpiredAt(v)
		return nil
	}
	return fmt.Errorf("unknown Teltent field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TeltentMutation) AddedFields() []string {
	var fields []string
	if m.addstatus != nil {
		fields = append(fields, teltent.FieldStatus)
	}
	if m.add_type != nil {
		fields = append(fields, teltent.FieldType)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TeltentMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case teltent.FieldStatus:
		return m.AddedStatus()
	case teltent.FieldType:
		return m.AddedType()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TeltentMutation) AddField(name string, value ent.Value) error {
	switch name {
	case teltent.FieldStatus:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStatus(v)
		return nil
	case teltent.FieldType:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddType(v)
		return nil
	}
	return fmt.Errorf("unknown Teltent numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TeltentMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(teltent.FieldDeletedAt) {
		fields = append(fields, teltent.FieldDeletedAt)
	}
	if m.FieldCleared(teltent.FieldExpiredAt) {
		fields = append(fields, teltent.FieldExpiredAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TeltentMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TeltentMutation) ClearField(name string) error {
	switch name {
	case teltent.FieldDeletedAt:
		m.ClearDeletedAt()
		return nil
	case teltent.FieldExpiredAt:
		m.ClearExpiredAt()
		return nil
	}
	return fmt.Errorf("unknown Teltent nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TeltentMutation) ResetField(name string) error {
	switch name {
	case teltent.FieldStatus:
		m.ResetStatus()
		return nil
	case teltent.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case teltent.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case teltent.FieldDeletedAt:
		m.ResetDeletedAt()
		return nil
	case teltent.FieldCertificateNo:
		m.ResetCertificateNo()
		return nil
	case teltent.FieldName:
		m.ResetName()
		return nil
	case teltent.FieldType:
		m.ResetType()
		return nil
	case teltent.FieldContactName:
		m.ResetContactName()
		return nil
	case teltent.FieldEmail:
		m.ResetEmail()
		return nil
	case teltent.FieldPhone:
		m.ResetPhone()
		return nil
	case teltent.FieldExpiredAt:
		m.ResetExpiredAt()
		return nil
	}
	return fmt.Errorf("unknown Teltent field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TeltentMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TeltentMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TeltentMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TeltentMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TeltentMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TeltentMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TeltentMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Teltent unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TeltentMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Teltent edge %s", name)
}
