// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/speech/fireworks-admin/internal/infrastructure/persistence/ent/predicate"
	"github.com/speech/fireworks-admin/internal/infrastructure/persistence/ent/teltent"
)

// TeltentUpdate is the builder for updating Teltent entities.
type TeltentUpdate struct {
	config
	hooks    []Hook
	mutation *TeltentMutation
}

// Where appends a list predicates to the TeltentUpdate builder.
func (_u *TeltentUpdate) Where(ps ...predicate.Teltent) *TeltentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeltentUpdate) SetStatus(v int8) *TeltentUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeltentUpdate) SetNillableStatus(v *int8) *TeltentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *TeltentUpdate) AddStatus(v int8) *TeltentUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeltentUpdate) SetUpdatedAt(v time.Time) *TeltentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TeltentUpdate) SetDeletedAt(v time.Time) *TeltentUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TeltentUpdate) SetNillableDeletedAt(v *time.Time) *TeltentUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TeltentUpdate) ClearDeletedAt() *TeltentUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCertificateNo sets the "certificate_no" field.
func (_u *TeltentUpdate) SetCertificateNo(v string) *TeltentUpdate {
	_u.mutation.SetCertificateNo(v)
	return _u
}

// SetNillableCertificateNo sets the "certificate_no" field if the given value is not nil.
func (_u *TeltentUpdate) SetNillableCertificateNo(v *string) *TeltentUpdate {
	if v != nil {
		_u.SetCertificateNo(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TeltentUpdate) SetName(v string) *TeltentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TeltentUpdate) SetNillableName(v *string) *TeltentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *TeltentUpdate) SetType(v int8) *TeltentUpdate {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TeltentUpdate) SetNillableType(v *int8) *TeltentUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *TeltentUpdate) AddType(v int8) *TeltentUpdate {
	_u.mutation.AddType(v)
	return _u
}

// SetContactName sets the "contact_name" field.
func (_u *TeltentUpdate) SetContactName(v string) *TeltentUpdate {
	_u.mutation.SetContactName(v)
	return _u
}

// SetNillableContactName sets the "contact_name" field if the given value is not nil.
func (_u *TeltentUpdate) SetNillableContactName(v *string) *TeltentUpdate {
	if v != nil {
		_u.SetContactName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *TeltentUpdate) SetEmail(v string) *TeltentUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *TeltentUpdate) SetNillableEmail(v *string) *TeltentUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *TeltentUpdate) SetPhone(v string) *TeltentUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *TeltentUpdate) SetNillablePhone(v *string) *TeltentUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *TeltentUpdate) SetExpiredAt(v time.Time) *TeltentUpdate {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *TeltentUpdate) SetNillableExpiredAt(v *time.Time) *TeltentUpdate {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *TeltentUpdate) ClearExpiredAt() *TeltentUpdate {
	_u.mutation.ClearExpiredAt()
	return _u
}

// Mutation returns the TeltentMutation object of the builder.
func (_u *TeltentUpdate) Mutation() *TeltentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeltentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeltentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeltentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeltentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeltentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teltent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeltentUpdate) check() error {
	if v, ok := _u.mutation.CertificateNo(); ok {
		if err := teltent.CertificateNoValidator(v); err != nil {
			return &ValidationError{Name: "certificate_no", err: fmt.Errorf(`ent: validator failed for field "Teltent.certificate_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := teltent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Teltent.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := teltent.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Teltent.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactName(); ok {
		if err := teltent.ContactNameValidator(v); err != nil {
			return &ValidationError{Name: "contact_name", err: fmt.Errorf(`ent: validator failed for field "Teltent.contact_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := teltent.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Teltent.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := teltent.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Teltent.phone": %w`, err)}
		}
	}
	return nil
}

func (_u *TeltentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teltent.Table, teltent.Columns, sqlgraph.NewFieldSpec(teltent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(teltent.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(teltent.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teltent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(teltent.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(teltent.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CertificateNo(); ok {
		_spec.SetField(teltent.FieldCertificateNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(teltent.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(teltent.FieldType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(teltent.FieldType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.ContactName(); ok {
		_spec.SetField(teltent.FieldContactName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(teltent.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(teltent.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(teltent.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(teltent.FieldExpiredAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teltent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeltentUpdateOne is the builder for updating a single Teltent entity.
type TeltentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeltentMutation
}

// SetStatus sets the "status" field.
func (_u *TeltentUpdateOne) SetStatus(v int8) *TeltentUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeltentUpdateOne) SetNillableStatus(v *int8) *TeltentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *TeltentUpdateOne) AddStatus(v int8) *TeltentUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeltentUpdateOne) SetUpdatedAt(v time.Time) *TeltentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TeltentUpdateOne) SetDeletedAt(v time.Time) *TeltentUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TeltentUpdateOne) SetNillableDeletedAt(v *time.Time) *TeltentUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TeltentUpdateOne) ClearDeletedAt() *TeltentUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCertificateNo sets the "certificate_no" field.
func (_u *TeltentUpdateOne) SetCertificateNo(v string) *TeltentUpdateOne {
	_u.mutation.SetCertificateNo(v)
	return _u
}

// SetNillableCertificateNo sets the "certificate_no" field if the given value is not nil.
func (_u *TeltentUpdateOne) SetNillableCertificateNo(v *string) *TeltentUpdateOne {
	if v != nil {
		_u.SetCertificateNo(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TeltentUpdateOne) SetName(v string) *TeltentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TeltentUpdateOne) SetNillableName(v *string) *TeltentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *TeltentUpdateOne) SetType(v int8) *TeltentUpdateOne {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TeltentUpdateOne) SetNillableType(v *int8) *TeltentUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *TeltentUpdateOne) AddType(v int8) *TeltentUpdateOne {
	_u.mutation.AddType(v)
	return _u
}

// SetContactName sets the "contact_name" field.
func (_u *TeltentUpdateOne) SetContactName(v string) *TeltentUpdateOne {
	_u.mutation.SetContactName(v)
	return _u
}

// SetNillableContactName sets the "contact_name" field if the given value is not nil.
func (_u *TeltentUpdateOne) SetNillableContactName(v *string) *TeltentUpdateOne {
	if v != nil {
		_u.SetContactName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *TeltentUpdateOne) SetEmail(v string) *TeltentUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *TeltentUpdateOne) SetNillableEmail(v *string) *TeltentUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *TeltentUpdateOne) SetPhone(v string) *TeltentUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *TeltentUpdateOne) SetNillablePhone(v *string) *TeltentUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *TeltentUpdateOne) SetExpiredAt(v time.Time) *TeltentUpdateOne {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *TeltentUpdateOne) SetNillableExpiredAt(v *time.Time) *TeltentUpdateOne {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *TeltentUpdateOne) ClearExpiredAt() *TeltentUpdateOne {
	_u.mutation.ClearExpiredAt()
	return _u
}

// Mutation returns the TeltentMutation object of the builder.
func (_u *TeltentUpdateOne) Mutation() *TeltentMutation {
	return _u.mutation
}

// Where appends a list predicates to the TeltentUpdate builder.
func (_u *TeltentUpdateOne) Where(ps ...predicate.Teltent) *TeltentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeltentUpdateOne) Select(field string, fields ...string) *TeltentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Teltent entity.
func (_u *TeltentUpdateOne) Save(ctx context.Context) (*Teltent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeltentUpdateOne) SaveX(ctx context.Context) *Teltent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeltentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeltentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeltentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teltent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeltentUpdateOne) check() error {
	if v, ok := _u.mutation.CertificateNo(); ok {
		if err := teltent.CertificateNoValidator(v); err != nil {
			return &ValidationError{Name: "certificate_no", err: fmt.Errorf(`ent: validator failed for field "Teltent.certificate_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := teltent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Teltent.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := teltent.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Teltent.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactName(); ok {
		if err := teltent.ContactNameValidator(v); err != nil {
			return &ValidationError{Name: "contact_name", err: fmt.Errorf(`ent: validator failed for field "Teltent.contact_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := teltent.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Teltent.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := teltent.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Teltent.phone": %w`, err)}
		}
	}
	return nil
}

func (_u *TeltentUpdateOne) sqlSave(ctx context.Context) (_node *Teltent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teltent.Table, teltent.Columns, sqlgraph.NewFieldSpec(teltent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Teltent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teltent.FieldID)
		for _, f := range fields {
			if !teltent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teltent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(teltent.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(teltent.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teltent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(teltent.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(teltent.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CertificateNo(); ok {
		_spec.SetField(teltent.FieldCertificateNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(teltent.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(teltent.FieldType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(teltent.FieldType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.ContactName(); ok {
		_spec.SetField(teltent.FieldContactName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(teltent.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(teltent.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(teltent.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(teltent.FieldExpiredAt, field.TypeTime)
	}
	_node = &Teltent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teltent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
