// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/speech/fireworks-admin/internal/infrastructure/persistence/ent/teltent"
)

// Teltent is the model entity for the Teltent schema.
type Teltent struct {
	config `json:"-"`
	// ID of the ent.
	// 主键
	ID uuid.UUID `json:"id,omitempty"`
	// 状态
	Status int8 `json:"status,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间，非空表示已软删除
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// 证件号码：企业-统一社会信用代码 个人-身份证号
	CertificateNo string `json:"certificate_no,omitempty"`
	// 租户名称
	Name string `json:"name,omitempty"`
	// 租户类型
	Type int8 `json:"type,omitempty"`
	// 联系人姓名
	ContactName string `json:"contact_name,omitempty"`
	// 联系邮箱
	Email string `json:"email,omitempty"`
	// 联系电话
	Phone string `json:"phone,omitempty"`
	// 过期时间
	ExpiredAt    time.Time `json:"expired_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Teltent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case teltent.FieldStatus, teltent.FieldType:
			values[i] = new(sql.NullInt64)
		case teltent.FieldCertificateNo, teltent.FieldName, teltent.FieldContactName, teltent.FieldEmail, teltent.FieldPhone:
			values[i] = new(sql.NullString)
		case teltent.FieldCreatedAt, teltent.FieldUpdatedAt, teltent.FieldDeletedAt, teltent.FieldExpiredAt:
			values[i] = new(sql.NullTime)
		case teltent.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Teltent fields.
func (_m *Teltent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case teltent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case teltent.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int8(value.Int64)
			}
		case teltent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case teltent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case teltent.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case teltent.FieldCertificateNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field certificate_no", values[i])
			} else if value.Valid {
				_m.CertificateNo = value.String
			}
		case teltent.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case teltent.FieldType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = int8(value.Int64)
			}
		case teltent.FieldContactName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_name", values[i])
			} else if value.Valid {
				_m.ContactName = value.String
			}
		case teltent.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case teltent.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				_m.Phone = value.String
			}
		case teltent.FieldExpiredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expired_at", values[i])
			} else if value.Valid {
				_m.ExpiredAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Teltent.
// This includes values selected through modifiers, order, etc.
func (_m *Teltent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Teltent.
// Note that you need to call Teltent.Unwrap() before calling this method if this Teltent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Teltent) Update() *TeltentUpdateOne {
	return NewTeltentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Teltent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Teltent) Unwrap() *Teltent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Teltent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Teltent) String() string {
	var builder strings.Builder
	builder.WriteString("Teltent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("certificate_no=")
	builder.WriteString(_m.CertificateNo)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("contact_name=")
	builder.WriteString(_m.ContactName)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(_m.Phone)
	builder.WriteString(", ")
	builder.WriteString("expired_at=")
	builder.WriteString(_m.ExpiredAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Teltents is a parsable slice of Teltent.
type Teltents []*Teltent
